//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "at.ac.tuwien.dsg.PRINGL.PRINGLDiagram")]

namespace at.ac.tuwien.dsg.PRINGL
{
	/// <summary>
	/// DomainClass PRINGLDiagram
	/// Description for at.ac.tuwien.dsg.PRINGL.PRINGLDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("at.ac.tuwien.dsg.PRINGL.PRINGLDiagram.DisplayName", typeof(global::at.ac.tuwien.dsg.PRINGL.PRINGLDomainModel), "at.ac.tuwien.dsg.PRINGL.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("at.ac.tuwien.dsg.PRINGL.PRINGLDiagram.Description", typeof(global::at.ac.tuwien.dsg.PRINGL.PRINGLDomainModel), "at.ac.tuwien.dsg.PRINGL.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::at.ac.tuwien.dsg.PRINGL.PRINGLDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("4f008b47-66fb-4dd5-b7e4-800871e87c6e")]
	public partial class PRINGLDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::at.ac.tuwien.dsg.PRINGL.PRINGLToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Compartment support
		/// <summary>
		/// Whether compartment items change events are subscribed to.
		/// </summary>
		private bool subscribedCompartmentItemsEvents;
		
		/// <summary>
		/// Subscribe to events fired when compartment items changes.
		/// </summary>
		public void SubscribeCompartmentItemsEvents()
		{
			if (!subscribedCompartmentItemsEvents && this.Store != null)
			{
				subscribedCompartmentItemsEvents = true;
				this.Store.EventManagerDirectory.ElementAdded.Add(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Add(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Add(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
			}
		}
		
		/// <summary>
		/// Unsubscribe to events fired when compartment items changes.
		/// </summary>
		public void UnsubscribeCompartmentItemsEvents()
		{
			if (subscribedCompartmentItemsEvents)
			{
				this.Store.EventManagerDirectory.ElementAdded.Remove(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Remove(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Remove(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
				subscribedCompartmentItemsEvents = false;
			}
		}
		
		#region Event handlers
		/// <summary>
		/// Event for element added.
		/// </summary>
		private void CompartmentItemAdded(object sender, DslModeling::ElementAddedEventArgs e)
		{
			// If in Undo, Redo or Rollback the compartment item rules are not run so we must refresh the compartment list at this point if required
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemAddRule.ElementAdded(e, repaintOnly);
		}
		/// <summary>
		/// Event for element deleted.
		/// </summary>
		private void CompartmentItemDeleted(object sender, DslModeling::ElementDeletedEventArgs e)
		{
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemDeleteRule.ElementDeleted(e, repaintOnly);
		}
		/// <summary>
		/// Event for element property changed.
		/// </summary>
		private void CompartmentItemPropertyChanged(object sender, DslModeling::ElementPropertyChangedEventArgs e)
		{
			bool repaintOnly = !e.ModelElement.Store.InUndoRedoOrRollback;
			CompartmentItemChangeRule.ElementPropertyChanged(e, repaintOnly);
		}
		/// <summary>
		/// Event for role-player changed.
		/// </summary>
		private void CompartmentItemRolePlayerChanged(object sender, DslModeling::RolePlayerChangedEventArgs e)
		{
			bool repaintOnly = !e.ElementLink.Store.InUndoRedoOrRollback;
			CompartmentItemRolePlayerChangeRule.RolePlayerChanged(e, repaintOnly);
		}
		/// <summary>
		/// Event for role-player order changed.
		/// </summary>
		private void CompartmentItemRolePlayerOrderChanged(object sender, DslModeling::RolePlayerOrderChangedEventArgs e)
		{
			bool repaintOnly = !e.Link.Store.InUndoRedoOrRollback;
			CompartmentItemRolePlayerPositionChangeRule.RolePlayerPositionChanged(e, repaintOnly);
		}
		#endregion
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::at.ac.tuwien.dsg.PRINGL.CompositeFilter)
			{
				global::at.ac.tuwien.dsg.PRINGL.CompositeFilterShape newShape = new global::at.ac.tuwien.dsg.PRINGL.CompositeFilterShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::at.ac.tuwien.dsg.PRINGL.CompositeAction)
			{
				global::at.ac.tuwien.dsg.PRINGL.CompositeActionShape newShape = new global::at.ac.tuwien.dsg.PRINGL.CompositeActionShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::at.ac.tuwien.dsg.PRINGL.Filter)
			{
				global::at.ac.tuwien.dsg.PRINGL.FilterShape newShape = new global::at.ac.tuwien.dsg.PRINGL.FilterShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::at.ac.tuwien.dsg.PRINGL.RewAction)
			{
				global::at.ac.tuwien.dsg.PRINGL.RewActionShape newShape = new global::at.ac.tuwien.dsg.PRINGL.RewActionShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::at.ac.tuwien.dsg.PRINGL.IncMech)
			{
				global::at.ac.tuwien.dsg.PRINGL.IncMechShape newShape = new global::at.ac.tuwien.dsg.PRINGL.IncMechShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::at.ac.tuwien.dsg.PRINGL.IncLogic)
			{
				global::at.ac.tuwien.dsg.PRINGL.IncLogicShape newShape = new global::at.ac.tuwien.dsg.PRINGL.IncLogicShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::at.ac.tuwien.dsg.PRINGL.PRINGLInstance)
			{
				global::at.ac.tuwien.dsg.PRINGL.InstanceShape newShape = new global::at.ac.tuwien.dsg.PRINGL.InstanceShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::at.ac.tuwien.dsg.PRINGL.IncMechInstance)
			{
				global::at.ac.tuwien.dsg.PRINGL.IncMechInstanceShape newShape = new global::at.ac.tuwien.dsg.PRINGL.IncMechInstanceShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::at.ac.tuwien.dsg.PRINGL.InnerFilterInstance)
			{
				global::at.ac.tuwien.dsg.PRINGL.InnerFilterShape newShape = new global::at.ac.tuwien.dsg.PRINGL.InnerFilterShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::at.ac.tuwien.dsg.PRINGL.InnerActionInstance)
			{
				global::at.ac.tuwien.dsg.PRINGL.InnerActionShape newShape = new global::at.ac.tuwien.dsg.PRINGL.InnerActionShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::at.ac.tuwien.dsg.PRINGL.InnerFilterFlow)
			{
				global::at.ac.tuwien.dsg.PRINGL.FilterFlowConnector newShape = new global::at.ac.tuwien.dsg.PRINGL.FilterFlowConnector(this.Partition);
				return newShape;
			}
			if(element is global::at.ac.tuwien.dsg.PRINGL.InnerActionFlow)
			{
				global::at.ac.tuwien.dsg.PRINGL.ActionFlowConnector newShape = new global::at.ac.tuwien.dsg.PRINGL.ActionFlowConnector(this.Partition);
				return newShape;
			}
			if(element is global::at.ac.tuwien.dsg.PRINGL.DefinitionReferencesInstance)
			{
				global::at.ac.tuwien.dsg.PRINGL.InstanceReferenceConnector newShape = new global::at.ac.tuwien.dsg.PRINGL.InstanceReferenceConnector(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::at.ac.tuwien.dsg.PRINGL.CompositeFilterShape.DecoratorsInitialized += CompositeFilterShapeDecoratorMap.OnDecoratorsInitialized;
			global::at.ac.tuwien.dsg.PRINGL.InnerFilterShape.DecoratorsInitialized += InnerFilterShapeDecoratorMap.OnDecoratorsInitialized;
			global::at.ac.tuwien.dsg.PRINGL.CompositeActionShape.DecoratorsInitialized += CompositeActionShapeDecoratorMap.OnDecoratorsInitialized;
			global::at.ac.tuwien.dsg.PRINGL.InnerActionShape.DecoratorsInitialized += InnerActionShapeDecoratorMap.OnDecoratorsInitialized;
			global::at.ac.tuwien.dsg.PRINGL.FilterShape.DecoratorsInitialized += FilterShapeDecoratorMap.OnDecoratorsInitialized;
			global::at.ac.tuwien.dsg.PRINGL.RewActionShape.DecoratorsInitialized += RewActionShapeDecoratorMap.OnDecoratorsInitialized;
			global::at.ac.tuwien.dsg.PRINGL.IncMechShape.DecoratorsInitialized += IncMechShapeDecoratorMap.OnDecoratorsInitialized;
			global::at.ac.tuwien.dsg.PRINGL.InstanceShape.DecoratorsInitialized += InstanceShapeDecoratorMap.OnDecoratorsInitialized;
			global::at.ac.tuwien.dsg.PRINGL.IncLogicShape.DecoratorsInitialized += IncLogicShapeDecoratorMap.OnDecoratorsInitialized;
			global::at.ac.tuwien.dsg.PRINGL.IncMechInstanceShape.DecoratorsInitialized += IncMechInstanceShapeDecoratorMap.OnDecoratorsInitialized;
			global::at.ac.tuwien.dsg.PRINGL.FilterFlowConnector.DecoratorsInitialized += FilterFlowConnectorDecoratorMap.OnDecoratorsInitialized;
			global::at.ac.tuwien.dsg.PRINGL.ActionFlowConnector.DecoratorsInitialized += ActionFlowConnectorDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for CompositeFilterShape.
		/// </summary>
		internal static partial class CompositeFilterShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for CompositeFilterShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.Container.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for InnerFilterShape.
		/// </summary>
		internal static partial class InnerFilterShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for InnerFilterShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.InnerFilterInstance.fullNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.InnerFilterInstance.PositionDomainPropertyId);
				propertyInfo.FilteringValues.Add("Final");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "FinalStateDecorator").AssociateVisibilityWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.InnerFilterInstance.PositionDomainPropertyId);
				propertyInfo.FilteringValues.Add("Initial");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "InitialStateDecorator").AssociateVisibilityWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for CompositeActionShape.
		/// </summary>
		internal static partial class CompositeActionShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for CompositeActionShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.Container.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for InnerActionShape.
		/// </summary>
		internal static partial class InnerActionShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for InnerActionShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.InnerActionInstance.fullNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.InnerActionInstance.PositionDomainPropertyId);
				propertyInfo.FilteringValues.Add("Initial");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "InitialStateDecorator").AssociateVisibilityWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.InnerActionInstance.PositionDomainPropertyId);
				propertyInfo.FilteringValues.Add("Final");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "FinalStateDecorator").AssociateVisibilityWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for FilterShape.
		/// </summary>
		internal static partial class FilterShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for FilterShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.Container.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for RewActionShape.
		/// </summary>
		internal static partial class RewActionShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for RewActionShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.Container.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for IncMechShape.
		/// </summary>
		internal static partial class IncMechShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for IncMechShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.Container.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for InstanceShape.
		/// </summary>
		internal static partial class InstanceShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for InstanceShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.Container.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.PRINGLInstance.MetatypeDomainPropertyId);
				propertyInfo.FilteringValues.Add("Action");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "IconDecoratorAction").AssociateVisibilityWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.PRINGLInstance.MetatypeDomainPropertyId);
				propertyInfo.FilteringValues.Add("Filter");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "IconDecoratorFilter").AssociateVisibilityWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.PRINGLInstance.MetatypeDomainPropertyId);
				propertyInfo.FilteringValues.Add("Logic");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "IconDecoratorLogic").AssociateVisibilityWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for IncLogicShape.
		/// </summary>
		internal static partial class IncLogicShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for IncLogicShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.Container.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.IncLogic.SubMetatypeDomainPropertyId);
				propertyInfo.FilteringValues.Add("ActionLogic");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ADecorator").AssociateVisibilityWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.IncLogic.SubMetatypeDomainPropertyId);
				propertyInfo.FilteringValues.Add("FilterLogic");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "FDecorator").AssociateVisibilityWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.IncLogic.SubMetatypeDomainPropertyId);
				propertyInfo.FilteringValues.Add("PredicateLogic");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "PDecorator").AssociateVisibilityWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.IncLogic.SubMetatypeDomainPropertyId);
				propertyInfo.FilteringValues.Add("StructureLogic");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "SDecorator").AssociateVisibilityWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.IncLogic.SubMetatypeDomainPropertyId);
				propertyInfo.FilteringValues.Add("TimeLogic");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TDecorator").AssociateVisibilityWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for IncMechInstanceShape.
		/// </summary>
		internal static partial class IncMechInstanceShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for IncMechInstanceShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.IncMechInstance.fullNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.IncMechInstance.priorityDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "PriorityDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for FilterFlowConnector.
		/// </summary>
		internal static partial class FilterFlowConnectorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for FilterFlowConnector.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.InnerFilterFlow.IsComplementedDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ComplementDecorator").AssociateVisibilityWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ActionFlowConnector.
		/// </summary>
		internal static partial class ActionFlowConnectorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ActionFlowConnector.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.InnerActionFlow.IsComplementedDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ComplementDecorator").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::at.ac.tuwien.dsg.PRINGL.InnerActionFlow.DelayDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "DelayDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::at.ac.tuwien.dsg.PRINGL.FilterFlowConnectAction filterFlowConnectAction;
		private global::at.ac.tuwien.dsg.PRINGL.ActionFlowConnectAction actionFlowConnectAction;
		private global::at.ac.tuwien.dsg.PRINGL.InstanceReferenceToolConnectAction instanceReferenceToolConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::at.ac.tuwien.dsg.PRINGL.PRINGLToolboxHelper.FilterFlowFilterString))
				{
					if (this.filterFlowConnectAction == null)
					{
						this.filterFlowConnectAction = new global::at.ac.tuwien.dsg.PRINGL.FilterFlowConnectAction(this);
						this.filterFlowConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.filterFlowConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::at.ac.tuwien.dsg.PRINGL.PRINGLToolboxHelper.ActionFlowFilterString))
				{
					if (this.actionFlowConnectAction == null)
					{
						this.actionFlowConnectAction = new global::at.ac.tuwien.dsg.PRINGL.ActionFlowConnectAction(this);
						this.actionFlowConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.actionFlowConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::at.ac.tuwien.dsg.PRINGL.PRINGLToolboxHelper.InstanceReferenceToolFilterString))
				{
					if (this.instanceReferenceToolConnectAction == null)
					{
						this.instanceReferenceToolConnectAction = new global::at.ac.tuwien.dsg.PRINGL.InstanceReferenceToolConnectAction(this);
						this.instanceReferenceToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.instanceReferenceToolConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.filterFlowConnectAction != null)
					{
						this.filterFlowConnectAction.Dispose();
						this.filterFlowConnectAction = null;
					}
					if(this.actionFlowConnectAction != null)
					{
						this.actionFlowConnectAction.Dispose();
						this.actionFlowConnectAction = null;
					}
					if(this.instanceReferenceToolConnectAction != null)
					{
						this.instanceReferenceToolConnectAction.Dispose();
						this.instanceReferenceToolConnectAction = null;
					}
					this.UnsubscribeCompartmentItemsEvents();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// PRINGLDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x4f008b47, 0x66fb, 0x4dd5, 0xb7, 0xe4, 0x80, 0x08, 0x71, 0xe8, 0x7c, 0x6e);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public PRINGLDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public PRINGLDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace at.ac.tuwien.dsg.PRINGL
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.CompositeFilter), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.CompositeAction), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.Filter), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.RewAction), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.IncMech), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.IncLogic), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.PRINGLInstance), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.IncMechInstance), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.InnerFilterInstance), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.InnerActionInstance), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.InnerFilterFlow), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.InnerActionFlow), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.DefinitionReferencesInstance), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::at.ac.tuwien.dsg.PRINGL.CompositeFilter)
				{
					parentElement = GetParentForCompositeFilter((global::at.ac.tuwien.dsg.PRINGL.CompositeFilter)childElement);
				} else
				if(childElement is global::at.ac.tuwien.dsg.PRINGL.CompositeAction)
				{
					parentElement = GetParentForCompositeAction((global::at.ac.tuwien.dsg.PRINGL.CompositeAction)childElement);
				} else
				if(childElement is global::at.ac.tuwien.dsg.PRINGL.Filter)
				{
					parentElement = GetParentForFilter((global::at.ac.tuwien.dsg.PRINGL.Filter)childElement);
				} else
				if(childElement is global::at.ac.tuwien.dsg.PRINGL.RewAction)
				{
					parentElement = GetParentForRewAction((global::at.ac.tuwien.dsg.PRINGL.RewAction)childElement);
				} else
				if(childElement is global::at.ac.tuwien.dsg.PRINGL.IncMech)
				{
					parentElement = GetParentForIncMech((global::at.ac.tuwien.dsg.PRINGL.IncMech)childElement);
				} else
				if(childElement is global::at.ac.tuwien.dsg.PRINGL.IncLogic)
				{
					parentElement = GetParentForIncLogic((global::at.ac.tuwien.dsg.PRINGL.IncLogic)childElement);
				} else
				if(childElement is global::at.ac.tuwien.dsg.PRINGL.PRINGLInstance)
				{
					parentElement = GetParentForPRINGLInstance((global::at.ac.tuwien.dsg.PRINGL.PRINGLInstance)childElement);
				} else
				if(childElement is global::at.ac.tuwien.dsg.PRINGL.IncMechInstance)
				{
					parentElement = GetParentForIncMechInstance((global::at.ac.tuwien.dsg.PRINGL.IncMechInstance)childElement);
				} else
				if(childElement is global::at.ac.tuwien.dsg.PRINGL.InnerFilterInstance)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForInnerFilterInstance(InnerFilterInstance childElement)
					// {
					// }
					// must be implemented in a partial class of at.ac.tuwien.dsg.PRINGL.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForInnerFilterInstance((global::at.ac.tuwien.dsg.PRINGL.InnerFilterInstance)childElement);
				} else
				if(childElement is global::at.ac.tuwien.dsg.PRINGL.InnerActionInstance)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForInnerActionInstance(InnerActionInstance childElement)
					// {
					// }
					// must be implemented in a partial class of at.ac.tuwien.dsg.PRINGL.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForInnerActionInstance((global::at.ac.tuwien.dsg.PRINGL.InnerActionInstance)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::at.ac.tuwien.dsg.PRINGL.IncentiveStrategy GetParentForCompositeFilter( global::at.ac.tuwien.dsg.PRINGL.IncentiveElement root )
			{
				// Segments 0 and 1
				global::at.ac.tuwien.dsg.PRINGL.IncentiveStrategy result = root.IncentiveStrategy;
				if ( result == null ) return null;
				return result;
			}
			public static global::at.ac.tuwien.dsg.PRINGL.IncentiveStrategy GetParentForCompositeAction( global::at.ac.tuwien.dsg.PRINGL.IncentiveElement root )
			{
				// Segments 0 and 1
				global::at.ac.tuwien.dsg.PRINGL.IncentiveStrategy result = root.IncentiveStrategy;
				if ( result == null ) return null;
				return result;
			}
			public static global::at.ac.tuwien.dsg.PRINGL.IncentiveStrategy GetParentForFilter( global::at.ac.tuwien.dsg.PRINGL.IncentiveElement root )
			{
				// Segments 0 and 1
				global::at.ac.tuwien.dsg.PRINGL.IncentiveStrategy result = root.IncentiveStrategy;
				if ( result == null ) return null;
				return result;
			}
			public static global::at.ac.tuwien.dsg.PRINGL.IncentiveStrategy GetParentForRewAction( global::at.ac.tuwien.dsg.PRINGL.IncentiveElement root )
			{
				// Segments 0 and 1
				global::at.ac.tuwien.dsg.PRINGL.IncentiveStrategy result = root.IncentiveStrategy;
				if ( result == null ) return null;
				return result;
			}
			public static global::at.ac.tuwien.dsg.PRINGL.IncentiveStrategy GetParentForIncMech( global::at.ac.tuwien.dsg.PRINGL.IncentiveElement root )
			{
				// Segments 0 and 1
				global::at.ac.tuwien.dsg.PRINGL.IncentiveStrategy result = root.IncentiveStrategy;
				if ( result == null ) return null;
				return result;
			}
			public static global::at.ac.tuwien.dsg.PRINGL.IncentiveStrategy GetParentForPRINGLInstance( global::at.ac.tuwien.dsg.PRINGL.IncentiveElement root )
			{
				// Segments 0 and 1
				global::at.ac.tuwien.dsg.PRINGL.IncentiveStrategy result = root.IncentiveStrategy;
				if ( result == null ) return null;
				return result;
			}
			public static global::at.ac.tuwien.dsg.PRINGL.IncentiveStrategy GetParentForIncLogic( global::at.ac.tuwien.dsg.PRINGL.IncentiveElement root )
			{
				// Segments 0 and 1
				global::at.ac.tuwien.dsg.PRINGL.IncentiveStrategy result = root.IncentiveStrategy;
				if ( result == null ) return null;
				return result;
			}
			public static global::at.ac.tuwien.dsg.PRINGL.IncentiveStrategy GetParentForIncMechInstance( global::at.ac.tuwien.dsg.PRINGL.IncentiveElement root )
			{
				// Segments 0 and 1
				global::at.ac.tuwien.dsg.PRINGL.IncentiveStrategy result = root.IncentiveStrategy;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
		/// <summary>
		/// Rule to update compartments when an item is added to the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemAddRule : DslModeling::AddRule
		{
			/// <summary>
			/// Called when an element is added. 
			/// </summary>
			/// <param name="e"></param>
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				ElementAdded(e, false);
			}
	
			internal static void ElementAdded(DslModeling::ElementAddedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if (e.ModelElement.IsDeleted)
					return;
				if(e.ModelElement is global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)
				{
					global::System.Collections.IEnumerable elements = GetFilterForFilterShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)e.ModelElement);
					UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.FilterShape), "Params", repaintOnly);
				}
				if(e.ModelElement is global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)
				{
					global::System.Collections.IEnumerable elements = GetRewActionForRewActionShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)e.ModelElement);
					UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.RewActionShape), "Params", repaintOnly);
				}
				if(e.ModelElement is global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)
				{
					global::System.Collections.IEnumerable elements = GetIncMechForIncMechShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)e.ModelElement);
					UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncMechShape), "Params", repaintOnly);
				}
				if(e.ModelElement is global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)
				{
					global::System.Collections.IEnumerable elements = GetIncLogicForIncLogicShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)e.ModelElement);
					UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncLogicShape), "Params", repaintOnly);
				}
				if(e.ModelElement is global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)
				{
					global::System.Collections.IEnumerable elements = GetIncMechInstanceForIncMechInstanceShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)e.ModelElement);
					UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncMechInstanceShape), "Params", repaintOnly);
				}
			}
			
			#region static DomainPath traversal methods to get the list of compartments to update
			internal static global::System.Collections.ICollection GetFilterForFilterShapeParamsFromLastLink(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters root)
			{
				// Segment 0
				global::at.ac.tuwien.dsg.PRINGL.IncentiveElement result = root.IncentiveElement;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetFilterForFilterShapeParams(global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter root)
			{
				// Segments 1 and 0
				global::at.ac.tuwien.dsg.PRINGL.IncentiveElement result = root.IncentiveElement;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetRewActionForRewActionShapeParamsFromLastLink(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters root)
			{
				// Segment 0
				global::at.ac.tuwien.dsg.PRINGL.IncentiveElement result = root.IncentiveElement;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetRewActionForRewActionShapeParams(global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter root)
			{
				// Segments 1 and 0
				global::at.ac.tuwien.dsg.PRINGL.IncentiveElement result = root.IncentiveElement;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetIncMechForIncMechShapeParamsFromLastLink(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters root)
			{
				// Segment 0
				global::at.ac.tuwien.dsg.PRINGL.IncentiveElement result = root.IncentiveElement;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetIncMechForIncMechShapeParams(global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter root)
			{
				// Segments 1 and 0
				global::at.ac.tuwien.dsg.PRINGL.IncentiveElement result = root.IncentiveElement;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetIncLogicForIncLogicShapeParamsFromLastLink(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters root)
			{
				// Segment 0
				global::at.ac.tuwien.dsg.PRINGL.IncentiveElement result = root.IncentiveElement;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetIncLogicForIncLogicShapeParams(global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter root)
			{
				// Segments 1 and 0
				global::at.ac.tuwien.dsg.PRINGL.IncentiveElement result = root.IncentiveElement;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetIncMechInstanceForIncMechInstanceShapeParamsFromLastLink(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters root)
			{
				// Segment 0
				global::at.ac.tuwien.dsg.PRINGL.IncentiveElement result = root.IncentiveElement;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetIncMechInstanceForIncMechInstanceShapeParams(global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter root)
			{
				// Segments 1 and 0
				global::at.ac.tuwien.dsg.PRINGL.IncentiveElement result = root.IncentiveElement;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			#endregion
	
			#region helper method to update compartments 
			/// <summary>
			/// Updates the compartments for the shapes associated to the given list of model elements
			/// </summary>
			/// <param name="elements">List of model elements</param>
			/// <param name="shapeType">The type of shape that needs updating</param>
			/// <param name="compartmentName">The name of the compartment to update</param>
			/// <param name="repaintOnly">If true, the method will only invalidate the shape for a repaint, without re-initializing the shape.</param>
			internal static void UpdateCompartments(global::System.Collections.IEnumerable elements, global::System.Type shapeType, string compartmentName, bool repaintOnly)
			{
				foreach (DslModeling::ModelElement element in elements)
				{
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
					foreach (DslDiagrams::PresentationElement pel in pels)
					{
						DslDiagrams::CompartmentShape compartmentShape = pel as DslDiagrams::CompartmentShape;
						if (compartmentShape != null && shapeType.IsAssignableFrom(compartmentShape.GetType()))
						{
							if (repaintOnly)
							{
								compartmentShape.Invalidate();
							}
							else
							{
								foreach(DslDiagrams::CompartmentMapping mapping in compartmentShape.GetCompartmentMappings())
								{
									if(mapping.CompartmentId==compartmentName)
									{
										mapping.InitializeCompartmentShape(compartmentShape);
										break;
									}
								}
							}
						}
					}
				}
			}
			#endregion
		}
		
		/// <summary>
		/// Rule to update compartments when an items is removed from the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemDeleteRule : DslModeling::DeleteRule
		{
			/// <summary>
			/// Called when an element is deleted
			/// </summary>
			/// <param name="e"></param>
			public override void ElementDeleted(DslModeling::ElementDeletedEventArgs e)
			{
				ElementDeleted(e, false);
			}
			
			internal static void ElementDeleted(DslModeling::ElementDeletedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetFilterForFilterShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.FilterShape), "Params", repaintOnly);
				}
				if(e.ModelElement is global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetRewActionForRewActionShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.RewActionShape), "Params", repaintOnly);
				}
				if(e.ModelElement is global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetIncMechForIncMechShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncMechShape), "Params", repaintOnly);
				}
				if(e.ModelElement is global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetIncLogicForIncLogicShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncLogicShape), "Params", repaintOnly);
				}
				if(e.ModelElement is global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetIncMechInstanceForIncMechInstanceShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncMechInstanceShape), "Params", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when the property on an item being displayed changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemChangeRule : DslModeling::ChangeRule 
		{
			/// <summary>
			/// Called when an element is changed
			/// </summary>
			/// <param name="e"></param>
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				ElementPropertyChanged(e, false);
			}
			
			internal static void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter && e.DomainProperty.Id == global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetFilterForFilterShapeParams((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.FilterShape), "Params", repaintOnly);
				}
				if(e.ModelElement is global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter && e.DomainProperty.Id == global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetRewActionForRewActionShapeParams((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.RewActionShape), "Params", repaintOnly);
				}
				if(e.ModelElement is global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter && e.DomainProperty.Id == global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetIncMechForIncMechShapeParams((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncMechShape), "Params", repaintOnly);
				}
				if(e.ModelElement is global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter && e.DomainProperty.Id == global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetIncLogicForIncLogicShapeParams((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncLogicShape), "Params", repaintOnly);
				}
				if(e.ModelElement is global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter && e.DomainProperty.Id == global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetIncMechInstanceForIncMechInstanceShapeParams((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncMechInstanceShape), "Params", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when a roleplayer change happens
		/// </summary>
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerChangeRule : DslModeling::RolePlayerChangeRule 
		{
			/// <summary>
			/// Called when the roleplayer on a link changes.
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				RolePlayerChanged(e, false);
			}
			
			internal static void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetFilterForFilterShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::at.ac.tuwien.dsg.PRINGL.FilterShape compartmentShape = pel as global::at.ac.tuwien.dsg.PRINGL.FilterShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetFilterForFilterShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.FilterShape), "Params", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetFilterForFilterShapeParams((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.FilterShape), "Params", repaintOnly);
					}
				}
				if(typeof(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetRewActionForRewActionShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::at.ac.tuwien.dsg.PRINGL.RewActionShape compartmentShape = pel as global::at.ac.tuwien.dsg.PRINGL.RewActionShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetRewActionForRewActionShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.RewActionShape), "Params", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetRewActionForRewActionShapeParams((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.RewActionShape), "Params", repaintOnly);
					}
				}
				if(typeof(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetIncMechForIncMechShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::at.ac.tuwien.dsg.PRINGL.IncMechShape compartmentShape = pel as global::at.ac.tuwien.dsg.PRINGL.IncMechShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetIncMechForIncMechShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncMechShape), "Params", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetIncMechForIncMechShapeParams((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncMechShape), "Params", repaintOnly);
					}
				}
				if(typeof(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetIncLogicForIncLogicShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::at.ac.tuwien.dsg.PRINGL.IncLogicShape compartmentShape = pel as global::at.ac.tuwien.dsg.PRINGL.IncLogicShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetIncLogicForIncLogicShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncLogicShape), "Params", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetIncLogicForIncLogicShapeParams((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncLogicShape), "Params", repaintOnly);
					}
				}
				if(typeof(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetIncMechInstanceForIncMechInstanceShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::at.ac.tuwien.dsg.PRINGL.IncMechInstanceShape compartmentShape = pel as global::at.ac.tuwien.dsg.PRINGL.IncMechInstanceShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetIncMechInstanceForIncMechInstanceShapeParamsFromLastLink((global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncMechInstanceShape), "Params", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetIncMechInstanceForIncMechInstanceShapeParams((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncMechInstanceShape), "Params", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// Rule to update compartments when the order of items in the list changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerPositionChangeRule : DslModeling::RolePlayerPositionChangeRule 
		{
			/// <summary>
			/// Called when the order of a roleplayer in a relationship changes
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e)
			{
				RolePlayerPositionChanged(e, false);
			}
			
			internal static void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetFilterForFilterShapeParams((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.FilterShape), "Params", repaintOnly);
					}
				}
				if(typeof(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetRewActionForRewActionShapeParams((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.RewActionShape), "Params", repaintOnly);
					}
				}
				if(typeof(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetIncMechForIncMechShapeParams((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncMechShape), "Params", repaintOnly);
					}
				}
				if(typeof(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetIncLogicForIncLogicShapeParams((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncLogicShape), "Params", repaintOnly);
					}
				}
				if(typeof(global::at.ac.tuwien.dsg.PRINGL.ElementHasParameters).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetIncMechInstanceForIncMechInstanceShapeParams((global::at.ac.tuwien.dsg.PRINGL.PRINGLParameter)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::at.ac.tuwien.dsg.PRINGL.IncMechInstanceShape), "Params", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.InnerActionFlow), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::at.ac.tuwien.dsg.PRINGL.InnerActionFlow.DelayDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::at.ac.tuwien.dsg.PRINGL.ActionFlowConnector.FindActionFlowConnectorDecorator("DelayDecorator");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::at.ac.tuwien.dsg.PRINGL.InnerActionFlow.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.InnerFilterFlow), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.InnerActionFlow), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::at.ac.tuwien.dsg.PRINGL.DefinitionReferencesInstance), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::at.ac.tuwien.dsg.PRINGL.PRINGLDiagram diagram = linkShape.Diagram as global::at.ac.tuwien.dsg.PRINGL.PRINGLDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
