//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace at.ac.tuwien.dsg.PRINGL
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "pringl";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"PRINGL";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"TU Wien";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID PRINGLDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PRINGLCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID PRINGLExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PRINGLCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewPRINGLExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PRINGLCommandSetId), 0x0001);
	
		// Package identifier
		public const string PRINGLPackageId = "ef6d6057-81a7-47e5-8884-1f6659772c0e";
		
		// Editor factory identifier
		public const string PRINGLEditorFactoryId = "c590e46a-0fd1-4cea-9f4f-7026eeb750ae";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string PRINGLModelExplorerToolWindowId = "c553fe08-b95c-4674-9147-b614ddf0272b";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace at.ac.tuwien.dsg.PRINGL
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string PRINGLCommandSetId = "a73e6898-1502-4924-a4ca-2923a5b452cc";
	}
}