//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace at.ac.tuwien.dsg.PRINGL
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\12.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(PRINGLExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(PRINGLExplorerToolWindow), Constants.PRINGLEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@DefinitionToolboxTab;at.ac.tuwien.dsg.PRINGL.Dsl.dll", "at.ac.tuwien.dsg.PRINGL.DefinitionToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("at.ac.tuwien.dsg.PRINGL.DefinitionToolboxTab",
					"@CompositeFilterToolToolboxItem;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					"at.ac.tuwien.dsg.PRINGL.CompositeFilterToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CompositeFilterTool", 
					"@CompositeFilterToolToolboxBitmap;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("at.ac.tuwien.dsg.PRINGL.DefinitionToolboxTab",
					"@CompositeActionToolToolboxItem;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					"at.ac.tuwien.dsg.PRINGL.CompositeActionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"CompositeActionTool", 
					"@CompositeActionToolToolboxBitmap;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("at.ac.tuwien.dsg.PRINGL.DefinitionToolboxTab",
					"@InnerFilterToolToolboxItem;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					"at.ac.tuwien.dsg.PRINGL.InnerFilterToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"InnerFilterTool", 
					"@InnerFilterToolToolboxBitmap;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("at.ac.tuwien.dsg.PRINGL.DefinitionToolboxTab",
					"@InnerActionToolToolboxItem;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					"at.ac.tuwien.dsg.PRINGL.InnerActionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"InnerActionTool", 
					"@InnerActionToolToolboxBitmap;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("at.ac.tuwien.dsg.PRINGL.DefinitionToolboxTab",
					"@FilterFlowToolboxItem;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					"at.ac.tuwien.dsg.PRINGL.FilterFlowToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"FilterFlow", 
					"@FilterFlowToolboxBitmap;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("at.ac.tuwien.dsg.PRINGL.DefinitionToolboxTab",
					"@ActionFlowToolboxItem;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					"at.ac.tuwien.dsg.PRINGL.ActionFlowToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ActionFlow", 
					"@ActionFlowToolboxBitmap;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideStaticToolboxItem("at.ac.tuwien.dsg.PRINGL.DefinitionToolboxTab",
					"@FilterToolToolboxItem;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					"at.ac.tuwien.dsg.PRINGL.FilterToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"FilterTool", 
					"@FilterToolToolboxBitmap;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					0xff00ff,
					Index = 6)]
	[VSShell::ProvideStaticToolboxItem("at.ac.tuwien.dsg.PRINGL.DefinitionToolboxTab",
					"@RewActionToolToolboxItem;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					"at.ac.tuwien.dsg.PRINGL.RewActionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"RewActionTool", 
					"@RewActionToolToolboxBitmap;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					0xff00ff,
					Index = 7)]
	[VSShell::ProvideStaticToolboxItem("at.ac.tuwien.dsg.PRINGL.DefinitionToolboxTab",
					"@IncMechToolToolboxItem;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					"at.ac.tuwien.dsg.PRINGL.IncMechToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"IncMechTool", 
					"@IncMechToolToolboxBitmap;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					0xff00ff,
					Index = 8)]
	[VSShell::ProvideStaticToolboxItem("at.ac.tuwien.dsg.PRINGL.DefinitionToolboxTab",
					"@IncLogicToolToolboxItem;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					"at.ac.tuwien.dsg.PRINGL.IncLogicToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"IncLogicTool", 
					"@IncLogicToolToolboxBitmap;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					0xff00ff,
					Index = 9)]
	[VSShell::ProvideStaticToolboxGroup("@DeclarationToolboxTab;at.ac.tuwien.dsg.PRINGL.Dsl.dll", "at.ac.tuwien.dsg.PRINGL.DeclarationToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("at.ac.tuwien.dsg.PRINGL.DeclarationToolboxTab",
					"@InstanceDeclarationToolToolboxItem;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					"at.ac.tuwien.dsg.PRINGL.InstanceDeclarationToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"InstanceDeclarationTool", 
					"@InstanceDeclarationToolToolboxBitmap;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					0xff00ff,
					Index = 10)]
	[VSShell::ProvideStaticToolboxItem("at.ac.tuwien.dsg.PRINGL.DeclarationToolboxTab",
					"@InstanceReferenceToolToolboxItem;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					"at.ac.tuwien.dsg.PRINGL.InstanceReferenceToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"InstanceReferenceTool", 
					"@InstanceReferenceToolToolboxBitmap;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					0xff00ff,
					Index = 11)]
	[VSShell::ProvideStaticToolboxItem("at.ac.tuwien.dsg.PRINGL.DeclarationToolboxTab",
					"@IncMechInstanceToolToolboxItem;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					"at.ac.tuwien.dsg.PRINGL.IncMechInstanceToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"IncMechInstanceTool", 
					"@IncMechInstanceToolToolboxBitmap;at.ac.tuwien.dsg.PRINGL.Dsl.dll", 
					0xff00ff,
					Index = 12)]
	[VSShell::ProvideEditorFactory(typeof(PRINGLEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(PRINGLEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(PRINGLEditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"PRINGL", typeof(PRINGLEditorFactory))]

	internal abstract partial class PRINGLPackageBase : DslShell::ModelingPackage
	{
		protected global::at.ac.tuwien.dsg.PRINGL.PRINGLToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new PRINGLEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::at.ac.tuwien.dsg.PRINGL.PRINGLToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			PRINGLCommandSet commandSet = new PRINGLCommandSet(this);
			commandSet.Initialize();
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			PRINGLClipboardCommandSet clipboardCommandSet = new PRINGLClipboardCommandSet(this);
			clipboardCommandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(PRINGLExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace at.ac.tuwien.dsg.PRINGL
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::at.ac.tuwien.dsg.PRINGL.PRINGLDirectiveProcessor), global::at.ac.tuwien.dsg.PRINGL.PRINGLDirectiveProcessor.PRINGLDirectiveProcessorName, "A directive processor that provides access to PRINGL files")]
	[global::System.Runtime.InteropServices.Guid(Constants.PRINGLPackageId)]
	internal sealed partial class PRINGLPackage : PRINGLPackageBase
	{
	}
}